version: "3.8"

services:

  birdgameapp:
    build: .
    container_name: birdgameapp
    ports:
      - "23003:3000"
    restart:
        "always"
    environment:
      NEXT_PUBLIC_BIRDIMAGE_URL: "https://xn--hyty-6qa.net/birds/"
